<?php

namespace App\Enums;

use ReflectionClass;

class CurrencyType
{
    const BDT = "BDT";
    const EUR = "EUR";
    const XOF = "XOF";
    const BGN = "BGN";
    const BAM = "BAM";
    const BBD = "BBD";
    const XPF = "XPF";
    const BMD = "BMD";
    const BND = "BND";
    const BOB = "BOB";
    const BHD = "BHD";
    const BIF = "BIF";
    const BTN = "BTN";
    const NOK = "NOK";
    const BWP = "BWP";
    const WST = "WST";
    const USD = "USD";
    const BRL = "BRL";
    const BSD = "BSD";
    const GBP = "GBP";
    const BYR = "BYR";
    const BZD = "BZD";
    const RUB = "RUB";
    const RWF = "RWF";
    const RSD = "RSD";
    const TMT = "TMT";
    const TJS = "TJS";
    const RON = "RON";
    const NZD = "NZD";
    const GTQ = "GTQ";
    const XAF = "XAF";
    const JPY = "JPY";
    const GYD = "GYD";
    const GEL = "GEL";
    const XCD = "XCD";
    const GNF = "GNF";
    const GMD = "GMD";
    const DKK = "DKK";
    const GIP = "GIP";
    const GHS = "GHS";
    const OMR = "OMR";
    const TND = "TND";
    const JOD = "JOD";
    const HRK = "HRK";
    const HTG = "HTG";
    const HUF = "HUF";
    const HKD = "HKD";
    const HNL = "HNL";
    const AUD = "AUD";
    const VEF = "VEF";
    const ILS = "ILS";
    const PYG = "PYG";
    const IQD = "IQD";
    const PAB = "PAB";
    const PGK = "PGK";
    const PEN = "PEN";
    const PKR = "PKR";
    const PHP = "PHP";
    const PLN = "PLN";
    const ZMK = "ZMK";
    const MAD = "MAD";
    const EGP = "EGP";
    const ZAR = "ZAR";
    const VND = "VND";
    const SBD = "SBD";
    const ETB = "ETB";
    const SOS = "SOS";
    const ZWL = "ZWL";
    const SAR = "SAR";
    const ERN = "ERN";
    const MDL = "MDL";
    const MGA = "MGA";
    const UZS = "UZS";
    const MMK = "MMK";
    const MOP = "MOP";
    const MNT = "MNT";
    const MKD = "MKD";
    const MUR = "MUR";
    const MWK = "MWK";
    const MVR = "MVR";
    const MRO = "MRO";
    const UGX = "UGX";
    const TZS = "TZS";
    const MYR = "MYR";
    const MXN = "MXN";
    const SHP = "SHP";
    const FJD = "FJD";
    const FKP = "FKP";
    const NIO = "NIO";
    const NAD = "NAD";
    const VUV = "VUV";
    const NGN = "NGN";
    const NPR = "NPR";
    const CHF = "CHF";
    const COP = "COP";
    const CNY = "CNY";
    const CLP = "CLP";
    const CAD = "CAD";
    const CDF = "CDF";
    const CZK = "CZK";
    const CRC = "CRC";
    const ANG = "ANG";
    const CVE = "CVE";
    const CUP = "CUP";
    const SZL = "SZL";
    const SYP = "SYP";
    const KGS = "KGS";
    const KES = "KES";
    const SSP = "SSP";
    const SRD = "SRD";
    const KHR = "KHR";
    const KMF = "KMF";
    const STD = "STD";
    const KRW = "KRW";
    const KPW = "KPW";
    const KWD = "KWD";
    const SLL = "SLL";
    const SCR = "SCR";
    const KZT = "KZT";
    const KYD = "KYD";
    const SGD = "SGD";
    const SEK = "SEK";
    const SDG = "SDG";
    const DOP = "DOP";
    const DJF = "DJF";
    const YER = "YER";
    const DZD = "DZD";
    const UYU = "UYU";
    const LBP = "LBP";
    const LAK = "LAK";
    const TWD = "TWD";
    const TTD = "TTD";
    const TRY = "TRY";
    const LKR = "LKR";
    const TOP = "TOP";
    const LTL = "LTL";
    const LRD = "LRD";
    const LSL = "LSL";
    const THB = "THB";
    const LYD = "LYD";
    const AED = "AED";
    const AFN = "AFN";
    const ISK = "ISK";
    const IRR = "IRR";
    const AMD = "AMD";
    const ALL = "ALL";
    const AOA = "AOA";
    const ARS = "ARS";
    const AWG = "AWG";
    const INR = "INR";
    const AZN = "AZN";
    const IDR = "IDR";
    const UAH = "UAH";
    const QAR = "QAR";
    const MZN = "MZN";

    public static function getItems() : array
    {
        $class = new ReflectionClass(__CLASS__);
        $items = [];
        foreach ($class->getConstants() as $item)
        {
            array_push($items, $item);
        }
        return $items;
    }
}
